import { ThemeProvider } from "next-themes"
import ClientLayout from "./_components/ClientLayout";
import "./globals.css";
import 'flowbite'
import { Toaster } from "@/components/ui/sonner";


export const metadata = {
  title: "Catalog | VAM Enterprises",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`antialiased`}
        >
          <ClientLayout>
            {children}
            <Toaster type="success"/>
          </ClientLayout>
        </body>
      </html>
    </ThemeProvider>
  );
}
